<?php
foreach( glob(dirname(__FILE__) . '/inc/*.php') as $file )
    require_once( $file );

/**
 * Implements hook_menu().
 */
function carrito_menu()
{
    $items = array();
    $items['carrito/add/%'] = array(
        'title' => 'Agregar jugador al carrito',
        'description' => 'Agrega un jugador al carrito de compras',
        'page callback' => 'carrito_add_player',
        'page arguments' => array(2),
        'access arguments' => array('access content'),
        'delivery callback' => 'carrito_add_player_ajax',
    );
    $items['carrito/checkout'] = array(
        'title' => 'Realiza checkout',
        'description' => 'Reliza la compra de jugadores',
        'page callback' => 'carrito_checkout',
        'access arguments' => array('access content'),
        'delivery callback' => 'carrito_checkout_ajax',
    );
    $items['carrito/sell/%/%'] = array(
        'title' => 'Venta',
        'description' => 'Venta de jugadores',
        'page callback' => 'carrito_sell',
        'page arguments' => array(2,3),
        'access callback' => 'user_is_logged_in',
    );
    $items['carrito/delete/%'] = array(
        'title' => 'Eliminar jugador del carrito',
        'description' => 'limina un jugador del carrito de compras',
        'page callback' => 'carrito_delete_player',
        'page arguments' => array(2),
        'access arguments' => array('access content'),
        'delivery callback' => 'carrito_delete_player_ajax',
    );
    return $items;
}


/**
 * Implements hook_theme().
 */
function carrito_theme($existing, $type, $theme, $path) {
    $hooks = array();
    $hooks['carrito'] = array(
        'variables' => array('data' => array()),
        'template' => "templates/carrito"
    );
    $hooks['checkout'] = array(
        'variables' => array('data' => array()),
        'template' => "templates/checkout"
    );
    $hooks['equipo'] = array(
        'variables' => array('data' => array()),
        'template' => "templates/equipo"
    );
    $hooks['agregar'] = array(
        'variables' => array('data' => array()),
        'template' => "templates/agregar"
    );
    return $hooks;
}
/**
 * Implements hook_hook_info().
 */
function carrito_block_info()
{
    $blocks = array();
    $blocks['carrito'] = array(
        'info' => t('Carrito de jugadores'),
        'cache' => DRUPAL_NO_CACHE,
    );
    $blocks['carrito2'] = array(
        'info' => t('Carrito de jugadores 2'),
        'cache' => DRUPAL_NO_CACHE,
    );
    $blocks['checkout'] = array(
        'info' => t('Opciones checkout'),
        'cache' => DRUPAL_NO_CACHE,
    );
    $blocks['equipo'] = array(
        'info' => t('Resumen de mi equipo'),
        'cache' => DRUPAL_NO_CACHE,
    );
    $blocks['equipo2'] = array(
        'info' => t('Resumen de mi equipo 2'),
        'cache' => DRUPAL_NO_CACHE,
    );
    $blocks['agregar'] = array(
        'info' => t('Agregar jugador'),
        'cache' => DRUPAL_NO_CACHE,
    );
    return $blocks;
}

/**
 * Implements hook_block_view().
 */
function carrito_block_view($delta = '')
{
    $block = array();
    switch ($delta) {
        case 'carrito':
        case 'carrito2':
            $block['content'] = theme('carrito', array('data' => carrito_data()));
            break;
        case 'checkout':
            $block['content'] = theme('checkout', array('data' => carrito_data()));
            break;
        case 'equipo':
        case 'equipo2':
            $block['content'] = theme('equipo', array('data' => equipo_data()));
            break;
        case 'agregar':
            $block['content'] = theme('agregar', array('data' => agregar_data()));
            break;
    }
    return $block;
}
