<?php
/**
 * Drupal Hooks globales para SoyDT
 */
foreach( glob(dirname(__FILE__) . '/inc/*.php') as $file )
    require_once( $file );


/**
 * Enable Views api
 */
function soydt_views_api(){
  return array(
      'api'  => 3,
      'path' => drupal_get_path( 'module', 'soydt' )
  );
}


/**
 * Implements hook_init
 */
function soydt_init() {
  // Crear una variable global con los datos de juego soydt para el usuario
  $equipo_usuario_nodes = carrito_get_equipo_usuario();
  $carrito_compras_node = get_carrito_compras();

  global $user_soydt;
  $user_soydt = new StdClass();
    if(isset($equipo_usuario_nodes->field_jugadores2[LANGUAGE_NONE]))
        $user_soydt->equipo_usuario = $equipo_usuario_nodes->field_jugadores2[LANGUAGE_NONE];
    else
        $user_soydt->equipo_usuario = array();
if(isset($carrito_compras_node->field_jugadores[LANGUAGE_NONE]))
    $user_soydt->carrito_compras = $carrito_compras_node->field_jugadores[LANGUAGE_NONE];
else
    $user_soydt->carrito_compras = array();
}


/**
 * Hook email_registration
 * Guarda como nombre de usuario el mismo texto del email.
 */
function soydt_email_registration_name($edit, $account) {
  return $edit['mail'];
}


/*
 * @ Hook user_presave
 * Renombra el "UserName" Cuando el usuario es actualizado
 * para que sea == al e-mail
 * En caso que no sea la cuenta de Admin (uid != 1)
 */
/* function soydt_user_presave(&$edit, $account, $category) {
  if($account->uid != 1)
    $edit['name'] = $edit['mail'];
}
*/

