<?php
/*
 Sincroniza los datos de eventos puntuables entre el dayscore y la tabla local para una fecha determinada.
*/
function obtener_eventos($fecha){
    $figuras = array();
    $request = drupal_http_request('http://dayscore.dayscript.com/minamin/services/eventsPlayersRound/'.$fecha);
    $data = drupal_json_decode($request->data);
    $table = data_get_table('dayscore_player_points');
    $keys = array("id_dayscript","id_round");
    foreach($data['list'][0]['teams'] as $equipo){
        foreach ($equipo as $jugador) {
            $jugador['id_dayscript'] = $jugador['id'];
            unset($jugador['id']);
            $jugador['id_round'] = $fecha;
            if(in_array($jugador['id_dayscript'],$figuras[$fecha])){
                $jugador['figura_directv'] = 1;
            } else {
                $jugador['figura_directv'] = 0;
            }
            $jugador['ptos_total']  =   0;

            $jugador['ptos_ini']    =   4*$jugador['init'];
            $jugador['ptos_total']  +=  $jugador['ptos_ini'];

            $jugador['ptos_sup']    =   2*$jugador['sup'];
            $jugador['ptos_total']  +=  $jugador['ptos_sup'];

            $jugador['ptos_figura'] =   10*$jugador['figura_directv'];
            $jugador['ptos_total']  +=  $jugador['ptos_figura'];

            if($jugador['position']==1)$value = 12;
            else if($jugador['position']==2)$value = 8;
            else if($jugador['position']==3)$value = 7;
            else $value = 6;
            $jugador['ptos_goles']  =   $value*($jugador['goal_foot']+$jugador['goal_head']+$jugador['goal_shot']);
            $jugador['ptos_total']  +=  $jugador['ptos_goles'];

            $jugador['ptos_penalgoal']  =   5*$jugador['penal_goal'];
            $jugador['ptos_total']  +=  $jugador['ptos_penalgoal'];

            $jugador['ptos_penalerr']  =   (-5)*$jugador['penal_err'];
            $jugador['ptos_total']  +=  $jugador['ptos_penalerr'];

            $jugador['ptos_penalcatch']  =   5*$jugador['penal_catch'];
            $jugador['ptos_total']  +=  $jugador['ptos_penalcatch'];

            $jugador['ptos_penalgoalx']  =   2*$jugador['penal_goalx'];
            $jugador['ptos_total']  +=  $jugador['ptos_penalgoalx'];

            $jugador['ptos_penalerrx']  =   (-3)*$jugador['penal_errx'];
            $jugador['ptos_total']  +=  $jugador['ptos_penalerrx'];

            $jugador['ptos_penalcatchx']  =   3*$jugador['penal_catchx'];
            $jugador['ptos_total']  +=  $jugador['ptos_penalcatchx'];

            $jugador['ptos_yellow']    =   (-2)*$jugador['card_yellow'];
            $jugador['ptos_total']  +=  $jugador['ptos_yellow'];

            $jugador['ptos_red']    =   (-5)*$jugador['card_red'];
            $jugador['ptos_total']  +=  $jugador['ptos_red'];

            if($jugador['position']==1)$value = 5;
            else if($jugador['position']==2)$value = 2;
            else $value = 0;
            $jugador['ptos_undefeated']  =   $value*$jugador['undefeated'];
            $jugador['ptos_total']  +=  $jugador['ptos_undefeated'];

            $jugador['ptos_autogoal']    =   (-5)*$jugador['autogoal'];
            $jugador['ptos_total']  +=  $jugador['ptos_autogoal'];

            $table->handler()->save($jugador,$keys);
            echo $jugador['id_dayscript'] . ": " . $jugador['ptos_total'] . "<br>";
        }
    }
    return 'Eventos sincronizados.';
}

