<?php

foreach( glob(dirname(__FILE__) . '/inc/*.php') as $file )
  require_once( $file );

/**
* Implements hook_init()
*/
// function alineaciones_init(){
// Los Archivos JS son cargados directamente desde el  tpl.php
// }


/**
* Implements hook_menu().
*/
function alineaciones_menu(){
  $items = array();

  //-----Pagina de Juego------
  $items['jugar/alineaciones/%'] = array(
    'title' => 'Alineaciones',
    // 'page callback' => 'theme',
    'page arguments' => array(2),
    'page callback' => 'alineaciones_page_cb',
    'access callback' => 'user_is_logged_in',
    'type' => MENU_CALLBACK,
    );

  //-----Filtros del formulario------
  $items['jugar/formacion/%/%'] = array(
    'title' => 'Cambiar formacion',
    'description' => 'Cambia la formacion de una alineacion',
    'page callback' => 'alineaciones_cambio_formacion',
    'page arguments' => array(2,3),
    'access callback' => 'user_is_logged_in',
    // 'access arguments' => array('access content'),
    // 'delivery callback' => 'alineaciones_cambio_formacion_ajax',
    );
  $items['jugar/capitan/%/%'] = array(
    'title' => 'Cambiar capitan',
    'description' => 'Cambia el capitan de una alineacion',
    'page callback' => 'alineaciones_cambio_capitan',
    'page arguments' => array(2,3),
    'access callback' => 'user_is_logged_in',
    // 'access arguments' => array('access content'),
    // 'delivery callback' => 'alineaciones_cambio_capitan_ajax',
    );
  $items['jugar/alinear/%/%/%'] = array(
    'title' => 'Alinear jugador',
    'description' => 'Asigna una posicion a un jugador',
    'page callback' => 'alineaciones_alinear_jugador',
    'page arguments' => array(2,3,4),
    'access callback' => 'user_is_logged_in',
    // 'access arguments' => array('access content'),
    'delivery callback' => 'alineaciones_alinear_jugador_ajax',
    );

  //-----Utilidades------
  $items['jugar/detallejugador/%'] = array(
    'title' => 'Detalle jugador',
    'description' => 'Muestra la ficha del jugador',
    'page callback' => 'alineaciones_jugador_detalle',
    'page arguments' => array(2),
    'access callback' => 'user_is_logged_in',
    // 'access arguments' => array('access content'),
    'delivery callback' => 'alineaciones_jugador_detalle_ajax',
    );
  $items['jugar/desalinear/%/%'] = array(
    'title' => 'Desalinear jugador',
    'description' => 'Desasigna una posicion a un jugador',
    'page callback' => 'alineaciones_desalinear_jugador',
    'page arguments' => array(2,3),
    'access callback' => 'user_is_logged_in',
    // 'access arguments' => array('access content'),
    // 'delivery callback' => 'alineaciones_desalinear_jugador_ajax',
    );
    $items['jugar/autoalinear/%/%'] = array(
        'title' => 'Alinear jugador en una posicion disponible',
        'description' => 'Asigna una posicion a un jugador',
        'page callback' => 'alineaciones_autoalinear_jugador',
        'page arguments' => array(2,3),
        'access callback' => 'user_is_logged_in',
    );
    $items['jugar/cancha'] = array(
      'title' => 'Cancha',
      'page callback' => '_cancha_block_cb',
      'access callback' => 'user_is_logged_in',
      );

    //-----Temp API------
    $items['api/jugar/estadio/%'] = array(
      'title' => 'Alineacion activa',
      'page callback' => 'alineaciones_api_estadio_cb',
      'access callback' => 'user_is_logged_in',
      'page arguments' => array(3)
      );
  return $items;
}



/**
* Implements hook_block_info
*/
function alineaciones_block_info() {
  $blocks = array();

  // Bloque para la integración con solo jQuery
  $blocks['estadio'] = array(
    'info' => t('Alineaciones - Cancha'),
    );

  // Bloque para la integración con AngularJS
  $blocks['estadio-angular'] = array(
    'info' => t('Alineaciones - Cancha (Angular) - Alpha Version'),
    );

  return $blocks;
}


/**
* Implements hook_block_view
*/
function alineaciones_block_view($delta='') {
  $block = array();

  switch($delta) {

    // Bloque para la integración con solo jQuery
    case 'estadio' :
    $variables = array();
    $block['content'] = theme('estadio', $variables);
    break;

    // Bloque para la integración con AngularJS
    case 'estadio-angular' :
    $variables = array();
    $block['content'] = theme('estadio-angular', $variables);
    break;
  }
  return $block;
}


/**
* Implements hook_theme().
*/
function alineaciones_theme($existing, $type, $theme, $path){
  $hooks = array();

  // Bloque para la integración con solo jQuery
  $hooks['estadio'] = array(
    'variables' => array(),
    'template' => 'templates/block--alineaciones',
    'cache' => DRUPAL_NO_CACHE,
    );

  // Bloque para la integración con AngularJS
  $hooks['estadio-angular'] = array(
    'variables' => array(),
    'template' => 'templates/block--angular-alineaciones',
    'cache' => DRUPAL_NO_CACHE,
    );
  return $hooks;
}



