<?php

foreach( glob(dirname(__FILE__) . '/inc/*.php') as $file )
  require_once( $file );

/**
* Implements hook_init()
*/
// function alineaciones_init(){
// Los Archivos JS son cargados directamente desde el  tpl.php
// }


/**
* Implements hook_menu().
*/
function alineaciones_menu(){
  $items = array();

  //-----Pagina de Juego------
  $items['jugar/alineaciones/%'] = array(
    'title' => 'Alineaciones',
    // 'page callback' => 'theme',
    'page callback' => 'alineaciones_page_cb',
    'page arguments' => array('alineacion'),
    'access callback' => 'user_is_logged_in',
    'type' => MENU_CALLBACK,
    );

  //-----Filtros del formulario------
  $items['jugar/formacion/%/%'] = array(
    'title' => 'Cambiar formacion',
    'description' => 'Cambia la formacion de una alineacion',
    'page callback' => 'alineaciones_cambio_formacion',
    'page arguments' => array(2,3),
    'access callback' => 'user_is_logged_in',
    // 'access arguments' => array('access content'),
    // 'delivery callback' => 'alineaciones_cambio_formacion_ajax',
    );
  $items['jugar/capitan/%/%'] = array(
    'title' => 'Cambiar capitan',
    'description' => 'Cambia el capitan de una alineacion',
    'page callback' => 'alineaciones_cambio_capitan',
    'page arguments' => array(2,3),
    'access callback' => 'user_is_logged_in',
    // 'access arguments' => array('access content'),
    // 'delivery callback' => 'alineaciones_cambio_capitan_ajax',
    );
  $items['jugar/alinear/%/%/%'] = array(
    'title' => 'Alinear jugador',
    'description' => 'Asigna una posicion a un jugador',
    'page callback' => 'alineaciones_alinear_jugador',
    'page arguments' => array(2,3,4),
    'access callback' => 'user_is_logged_in',
    // 'access arguments' => array('access content'),
    // 'delivery callback' => 'alineaciones_alinear_jugador_ajax',
    );

  //-----Utilidades------
  $items['jugar/detallejugador/%'] = array(
    'title' => 'Detalle jugador',
    'description' => 'Muestra la ficha del jugador',
    'page callback' => 'alineaciones_jugador_detalle',
    'page arguments' => array(2),
    'access callback' => 'user_is_logged_in',
    // 'access arguments' => array('access content'),
    // 'delivery callback' => 'alineaciones_jugador_detalle_ajax',
    );
  $items['jugar/desalinear/%/%'] = array(
    'title' => 'Desalinear jugador',
    'description' => 'Desasigna una posicion a un jugador',
    'page callback' => 'alineaciones_desalinear_jugador',
    'page arguments' => array(2,),
    'access callback' => 'user_is_logged_in',
    // 'access arguments' => array('access content'),
    // 'delivery callback' => 'alineaciones_desalinear_jugador_ajax',
    );

  return $items;
}



/**
* Implements hook_block_info
*/
function alineaciones_block_info() {
  $blocks = array();

  $blocks['estadio'] = array(
    'info' => t('Alineaciones - Cancha'),
    );

  return $blocks;
}


/**
* Implements hook_block_view
*/
function alineaciones_block_view($delta='') {
  $block = array();

  switch($delta) {
    case 'estadio' :
    $variables = array();
    $block['content'] = theme('estadio', $variables);
    break;
  }
  return $block;
}


/**
* Implements hook_theme().
*/
function alineaciones_theme($existing, $type, $theme, $path){
  $hooks = array();
  $hooks['estadio'] = array(
    'variables' => array(),
    'template' => 'templates/block--alineaciones',
    'cache' => DRUPAL_NO_CACHE,
    );
  return $hooks;
}



